// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amuypyniqbizahbgfrbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtdXlweW5pcWJpemFoYmdmcmJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQxMzk4ODgsImV4cCI6MjA5OTcxNTg4OH0.z60IZo72mbM1IRuMsURWfoUHQszfmLQc3PeZYkxjYKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});